MAX_LONG_DURATION = 99
STARNDART_LONG_R_DURATION = 15
MIN_LONG_DURATION = 1

MAX_SHORT_DURATION = 99
STANDART_SHORT_R_DURATION = 5
MIN_SHORT_DURATION = 1

MAX_WORK_DURATION = 99
STANDART_WORK_DURATION = 25
MIN_WORK_DURATION = 1

MIN_SESSIONS = 1
STANDART_SESSIONS = 4
MAX_SESSIONS = 10
