"""pomodoro

Revision ID: ee8db6a1c866
Revises: 52245710d998
Create Date: 2023-03-25 17:04:06.906439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee8db6a1c866'
down_revision = '52245710d998'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pomodoro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_rest_duration', sa.Integer(), nullable=True),
    sa.Column('long_rest_duration', sa.Integer(), nullable=True),
    sa.Column('work_duration', sa.Integer(), nullable=True),
    sa.Column('number_of_sessions', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pomodoro_id'), 'pomodoro', ['id'], unique=False)
    op.create_index(op.f('ix_pomodoro_user_id'), 'pomodoro', ['user_id'], unique=False)
    op.create_table('history_of_pomodoro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utc_end', sa.DateTime(), nullable=False),
    sa.Column('duration_in_seconds', sa.Integer(), nullable=False),
    sa.Column('pomodoro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pomodoro_id'], ['pomodoro.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_of_pomodoro_id'), 'history_of_pomodoro', ['id'], unique=False)
    op.create_index(op.f('ix_history_of_pomodoro_pomodoro_id'), 'history_of_pomodoro', ['pomodoro_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_of_pomodoro_pomodoro_id'), table_name='history_of_pomodoro')
    op.drop_index(op.f('ix_history_of_pomodoro_id'), table_name='history_of_pomodoro')
    op.drop_table('history_of_pomodoro')
    op.drop_index(op.f('ix_pomodoro_user_id'), table_name='pomodoro')
    op.drop_index(op.f('ix_pomodoro_id'), table_name='pomodoro')
    op.drop_table('pomodoro')
    # ### end Alembic commands ###
