"""User_change

Revision ID: 52245710d998
Revises: e84ee13839a1
Create Date: 2023-03-19 11:25:59.277470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52245710d998'
down_revision = 'e84ee13839a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
